const quotes={
 AAPL:{name:'Apple',price:225.00,change:0.85,seed:[198,202,201,207,205,211,214,210,216,218,215,222,225]},
 MSFT:{name:'Microsoft',price:517.30,change:0.42,seed:[484,489,492,487,498,501,499,506,510,509,513,515,517]},
 NVDA:{name:'NVIDIA',price:184.20,change:-0.31,seed:[176,181,179,185,188,186,190,187,183,185,182,184,184.2]},
 SPY:{name:'S&P 500 ETF',price:672.10,change:0.18,seed:[657,660,661,659,663,666,664,668,669,667,670,671,672.1]}
};
const lessons=[
 {id:'stock',world:1,title:'What Is a Stock?',desc:'Ownership, shares and public companies',xp:100,copy:'A stock represents a fractional ownership interest in a company. Public companies issue shares that can trade between investors on exchanges. A stock price can move as buyers and sellers respond to new information, expectations and market conditions.',concept:'Owning a share means owning a small piece of the company — it does not guarantee a profit.',q:'What does one share of common stock generally represent?',choices:['A guaranteed return','Partial ownership in a company','A loan you made to a broker'],answer:1},
 {id:'exchange',world:1,title:'How Markets Work',desc:'Exchanges, buyers, sellers and liquidity',xp:100,copy:'Markets bring buyers and sellers together. Exchanges provide organized venues where orders can interact. Liquidity describes how easily an asset can be bought or sold without causing a large price change.',concept:'More liquidity generally means it is easier to enter or exit a position, but risk still remains.',q:'What does market liquidity describe?',choices:['How easily an asset can trade','How profitable a company is','How many employees a company has'],answer:0},
 {id:'bidask',world:1,title:'Bid vs. Ask',desc:'Understand the two sides of a quote',xp:120,copy:'The bid is the highest displayed price a buyer is offering, while the ask is the lowest displayed price a seller is willing to accept. The difference between them is called the spread.',concept:'A smaller bid-ask spread can reduce trading friction, but it does not remove market risk.',q:'Which price is normally associated with a seller?',choices:['The ask','The bid','The dividend'],answer:0},
 {id:'orders',world:2,title:'Market & Limit Orders',desc:'Control how an order can execute',xp:140,copy:'A market order prioritizes getting an execution, but the exact execution price can vary. A limit order sets the maximum price you will pay when buying or minimum price you will accept when selling, but it may never fill.',concept:'Market orders prioritize execution; limit orders prioritize price control.',q:'What is a key tradeoff of a limit order?',choices:['It always fills instantly','It may not execute','It guarantees a profit'],answer:1},
 {id:'risk',world:2,title:'Risk Management 101',desc:'Think about downside before upside',xp:160,copy:'Risk management is the process of deciding how much capital to expose, where a thesis becomes invalid and how one position fits within the rest of a portfolio. No single technique can eliminate losses.',concept:'A good simulator rewards disciplined decision-making, not just the biggest short-term return.',q:'What is the main purpose of position sizing?',choices:['To eliminate all losses','To control how much capital is exposed','To predict tomorrow’s price'],answer:1},
 {id:'diversify',world:2,title:'Diversification',desc:'Avoid relying on one outcome',xp:160,copy:'Diversification spreads exposure across different investments or risk sources. It can reduce the impact of one holding performing poorly, although it cannot guarantee against loss.',concept:'Diversification is about managing concentration risk — not guaranteeing positive returns.',q:'Diversification primarily helps address which risk?',choices:['Concentration risk','Password risk','Exchange opening hours'],answer:0},
 {id:'candles',world:3,title:'Candlestick Basics',desc:'Open, high, low and close',xp:180,copy:'A candlestick summarizes price movement over a chosen time interval. Its body typically shows the open and close, while its wicks show the high and low for that interval.',concept:'Candlesticks describe what price did; by themselves, they do not predict what price must do next.',q:'What do candle wicks usually indicate?',choices:['High and low prices','Company revenue','Dividend dates'],answer:0},
 {id:'trend',world:3,title:'Trend & Range',desc:'Describe market structure',xp:180,copy:'A trend is a persistent directional tendency in price, while a range describes price moving between relatively defined areas. These are descriptive frameworks, not guarantees that the same behavior will continue.',concept:'Market structure can change. Historical patterns are not promises.',q:'A market moving between relatively defined upper and lower areas is often called what?',choices:['A range','A dividend','A split'],answer:0},
 {id:'plan',world:4,title:'Build a Trade Plan',desc:'Define thesis, risk and exit before acting',xp:220,copy:'A trade plan records what you believe, what evidence would invalidate that idea, how much you are willing to risk and how you would exit. Writing the plan before a simulated trade can reduce impulsive decision-making.',concept:'The goal is a repeatable decision process — not certainty.',q:'When is the best time to define the invalidation point?',choices:['Before entering the trade','Only after a loss','It is never useful'],answer:0},
 {id:'journal',world:4,title:'Review & Journal',desc:'Learn from your own decisions',xp:220,copy:'A trading journal records the setup, reasoning, execution and outcome. Reviewing many decisions can reveal whether you followed your process and where mistakes repeat.',concept:'Judge your process across many decisions; one winning trade can still be poorly planned.',q:'What is a journal most useful for?',choices:['Guaranteeing the next winner','Reviewing decisions and process','Getting live brokerage access'],answer:1}
];
const worlds=[
 {id:1,title:'Market Foundations',subtitle:'Learn how public markets and quotes work.'},
 {id:2,title:'Orders & Risk',subtitle:'Practice execution, sizing and diversification.'},
 {id:3,title:'Read the Market',subtitle:'Understand charts without treating patterns as guarantees.'},
 {id:4,title:'Build Your Process',subtitle:'Plan, simulate and review decisions.'}
];
const badges=[
 {id:'first_lesson',icon:'📘',title:'First Quest',desc:'Complete your first lesson.',test:s=>s.completed.length>=1},
 {id:'world1',icon:'🧭',title:'Market Explorer',desc:'Complete the entire Market Foundations world.',test:s=>lessons.filter(l=>l.world===1).every(l=>s.completed.includes(l.id))},
 {id:'first_trade',icon:'⚡',title:'Paper Trader',desc:'Place your first simulated order.',test:s=>s.trades.length>=1},
 {id:'diverse',icon:'🧩',title:'Diversifier',desc:'Hold three simulated symbols at once.',test:s=>Object.keys(s.positions).filter(k=>s.positions[k].qty>0).length>=3},
 {id:'risk_world',icon:'🛡️',title:'Risk Guardian',desc:'Complete the Orders & Risk world.',test:s=>lessons.filter(l=>l.world===2).every(l=>s.completed.includes(l.id))},
 {id:'five_quests',icon:'🏆',title:'Quest Streak',desc:'Complete five learning quests.',test:s=>s.completed.length>=5}
];
let state=null,authMode='register',selected='AAPL',side='BUY',activeLesson=null;
function freshState(profile){return{profile,createdAt:Date.now(),xp:0,coins:100,streak:1,lastDaily:null,completed:[],positions:{},cash:10000,trades:[],earnedBadges:[]}}
function save(){if(!state)return;queueCloudSave();renderHeader()}
function setAuthMode(m){authMode=m;document.getElementById('registerTab').classList.toggle('active',m==='register');document.getElementById('loginTab').classList.toggle('active',m==='login');document.getElementById('nameField').style.display=m==='register'?'grid':'none';document.getElementById('authSubmit').textContent=m==='register'?'Create Free Account':'Log In'}
function submitAuth(event){return submitCloudAuth(event)}
function openAuth(){document.getElementById('authModal').classList.add('open')}
function closeAuth(){document.getElementById('authModal').classList.remove('open')}
function logout(){return cloudLogout()}
function resetProgress(){if(!state)return;let p=state.profile;state=freshState(p);save();closeProfile();renderAll();toast('Practice progress reset.')}
function touchStreak(){if(!state)return;let today=new Date().toISOString().slice(0,10),last=state.lastVisit;if(last&&last!==today){let d=Math.round((new Date(today)-new Date(last))/86400000);state.streak=d===1?state.streak+1:1}state.lastVisit=today;save()}
function xpLevel(){let total=state?.xp||0,level=Math.floor(total/500)+1,into=total%500;return{level,into,next:500,pct:Math.round(into/500*100)}}
function rankFor(level){return level>=8?'Market Master':level>=6?'Strategist':level>=4?'Analyst':level>=2?'Apprentice Trader':'Rookie Trader'}
function showView(name){if(!state&&name!=='dashboard')return openAuth();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+name).classList.add('active');if(name==='simulator')renderSimulator();if(name==='learn')renderWorlds();if(name==='achievements')renderAchievements();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){if(!state)return;renderHeader();renderDashboard();renderWorlds();renderSimulator();renderAchievements()}
function renderHeader(){if(!state)return;let lv=xpLevel().level;document.getElementById('headerLevel').textContent='LVL '+lv;document.getElementById('avatarBtn').textContent=state.profile.name[0].toUpperCase()}
function money(n){return '$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function portfolioInvested(){return Object.entries(state.positions).reduce((t,[sym,p])=>t+p.qty*quotes[sym].price,0)}
function portfolioValue(){return state.cash+portfolioInvested()}
function nextLesson(){return lessons.find(l=>!state.completed.includes(l.id))}
function worldUnlocked(n){if(n===1)return true;return lessons.filter(l=>l.world===n-1).every(l=>state.completed.includes(l.id))}
function renderDashboard(){let l=xpLevel(),n=nextLesson();document.getElementById('playerName').textContent=state.profile.name;document.getElementById('rankName').textContent=rankFor(l.level);document.getElementById('levelBadge').textContent=l.level;document.getElementById('xpText').textContent=`${l.into} / ${l.next} XP`;document.getElementById('xpPercent').textContent=l.pct+'%';document.getElementById('xpBar').style.width=l.pct+'%';document.getElementById('streakStat').textContent=state.streak+(state.streak===1?' day':' days');document.getElementById('coinsStat').textContent=state.coins.toLocaleString();document.getElementById('badgesStat').textContent=state.earnedBadges.length;document.getElementById('portfolioValue').textContent=money(portfolioValue());document.getElementById('dashCash').textContent=money(state.cash);document.getElementById('dashInvested').textContent=money(portfolioInvested());if(n){document.getElementById('nextMissionTitle').textContent=n.title;document.getElementById('nextMissionDesc').textContent=n.desc;document.getElementById('nextMissionXP').textContent=n.xp}else{document.getElementById('nextMissionTitle').textContent='Course Complete!';document.getElementById('nextMissionDesc').textContent='You completed every Phase 2 learning quest.';document.getElementById('nextMissionXP').textContent='0'}renderDaily()}
function continueQuest(){let n=nextLesson();if(!n){toast('You completed every Phase 2 quest!');return showView('achievements')}openLesson(n.id)}
function renderDaily(){let today=new Date().toISOString().slice(0,10),done=state.lastDaily===today,box=document.getElementById('dailyQuestion'),status=document.getElementById('dailyStatus');status.textContent=done?'COMPLETE':'AVAILABLE';box.innerHTML=done?'<p class="correct">✓ Daily quest complete. Come back tomorrow to continue your streak.</p>':`<p>Which order type sets a maximum buy price or minimum sell price?</p><div class="choice-list"><button data-tq-click="answerDaily(false)">Market order</button><button data-tq-click="answerDaily(true)">Limit order</button><button data-tq-click="answerDaily(false)">Dividend order</button></div>`}
function answerDaily(ok){if(!ok)return toast('Not quite — try again.');let today=new Date().toISOString().slice(0,10);if(state.lastDaily===today)return;state.lastDaily=today;addRewards(50,25);save();renderDashboard();toast('Daily quest complete! +50 XP • +25 coins')}
function addRewards(xp,coins){state.xp+=xp;state.coins+=coins;syncBadges()}
function renderWorlds(){if(!state)return;let complete=state.completed.length, pct=Math.round(complete/lessons.length*100);document.getElementById('courseProgress').textContent=pct+'%';document.getElementById('worlds').innerHTML=worlds.map(w=>{let unlocked=worldUnlocked(w.id),ls=lessons.filter(l=>l.world===w.id);return `<article class="world ${unlocked?'':'locked'}"><div class="world-head"><div class="world-num">${unlocked?w.id:'🔒'}</div><div><h2>${w.title}</h2><p>${w.subtitle}</p></div></div>${ls.map(l=>{let done=state.completed.includes(l.id);return `<div class="lesson-row ${done?'done':''} ${unlocked?'':'locked'}"><div class="lesson-dot">${done?'✓':unlocked?'▶':'🔒'}</div><div><h4>${l.title}</h4><small>${l.desc} • +${l.xp} XP</small></div><button ${unlocked?`data-tq-click="openLesson('${l.id}')"`:'disabled'}>${done?'Review':'Start'}</button></div>`}).join('')}</article>`}).join('')}
function openLesson(id){let l=lessons.find(x=>x.id===id);if(!l||!worldUnlocked(l.world))return;activeLesson=l;let done=state.completed.includes(id);document.getElementById('lessonContent').innerHTML=`<div class="lesson-body"><div class="lesson-kicker">WORLD ${l.world} • +${l.xp} XP</div><h2>${l.title}</h2><p class="lesson-copy">${l.copy}</p><div class="concept-box"><strong>Key idea:</strong> ${l.concept}</div><div class="quiz-block"><h3>Mission check</h3><p>${l.q}</p><div class="choice-list">${l.choices.map((c,i)=>`<button data-tq-click="answerLesson(${i})">${c}</button>`).join('')}</div><div id="quizResult" class="quiz-result">${done?'✓ Already completed — you can review this lesson anytime.':''}</div></div></div>`;document.getElementById('lessonModal').classList.add('open')}
function answerLesson(i){let l=activeLesson,res=document.getElementById('quizResult');if(i!==l.answer){res.className='quiz-result wrong';res.textContent='Not quite. Review the lesson and try again.';return}if(state.completed.includes(l.id)){res.className='quiz-result correct';res.textContent='✓ Correct — lesson already completed.';return}state.completed.push(l.id);addRewards(l.xp,Math.round(l.xp/4));save();res.className='quiz-result correct';res.textContent=`✓ Mission complete! +${l.xp} XP`;renderDashboard();renderWorlds();renderAchievements();toast(`Quest complete! +${l.xp} XP`)}
function closeLesson(){document.getElementById('lessonModal').classList.remove('open');activeLesson=null}
function renderSimulator(){if(!state)return;document.getElementById('simCash').textContent=money(state.cash);document.getElementById('symbolTabs').innerHTML=Object.keys(quotes).map(s=>`<button class="${s===selected?'active':''}" data-tq-click="selectSymbol('${s}')">${s}</button>`).join('');let q=quotes[selected];document.getElementById('selectedSymbol').textContent=selected;document.getElementById('selectedName').textContent=q.name;document.getElementById('quotePrice').textContent=money(q.price);document.getElementById('quoteChange').textContent=(q.change>=0?'+':'')+q.change.toFixed(2)+'%';document.getElementById('quoteChange').style.color=q.change>=0?'var(--green)':'var(--red)';renderChart();renderOrderTotal();renderPositions();renderHistory()}
function selectSymbol(s){selected=s;renderSimulator()}
function setSide(s){side=s;document.getElementById('buyTab').classList.toggle('active',s==='BUY');document.getElementById('sellTab').classList.toggle('active',s==='SELL');document.getElementById('placeOrderBtn').textContent='Place Simulated '+(s==='BUY'?'Buy':'Sell');renderOrderTotal()}
function renderOrderTotal(){let q=Number(document.getElementById('shareQty')?.value||1);document.getElementById('orderTotal').textContent=money(Math.max(1,q)*quotes[selected].price)}
function renderChart(){let svg=document.getElementById('priceChart'),arr=quotes[selected].seed,min=Math.min(...arr),max=Math.max(...arr),pad=Math.max((max-min)*.15,1),lo=min-pad,hi=max+pad;let pts=arr.map((v,i)=>{let x=i/(arr.length-1)*700,y=240-(v-lo)/(hi-lo)*215;return[x,y]});let line=pts.map(p=>p.join(',')).join(' '),poly=`0,260 ${line} 700,260`;svg.innerHTML=`<defs><linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#58f58b" stop-opacity=".24"/><stop offset="1" stop-color="#58f58b" stop-opacity="0"/></linearGradient></defs><polygon class="chart-fill" points="${poly}"/><polyline class="chart-line" points="${line}"/>`}
function placeOrder(){let qty=Math.floor(Number(document.getElementById('shareQty').value)||0),price=quotes[selected].price,total=qty*price;if(qty<1)return toast('Enter at least 1 share.');state.positions[selected] ||= {qty:0,cost:0};let p=state.positions[selected];if(side==='BUY'){if(total>state.cash)return toast('Not enough virtual cash for this simulated order.');let oldValue=p.qty*p.cost,newQty=p.qty+qty;p.cost=(oldValue+total)/newQty;p.qty=newQty;state.cash-=total}else{if(qty>p.qty)return toast('You do not own enough simulated shares to sell.');p.qty-=qty;state.cash+=total;if(p.qty===0)delete state.positions[selected]}state.trades.unshift({side,symbol:selected,qty,price,time:Date.now()});if(state.trades.length>20)state.trades.length=20;let first=state.trades.length===1;addRewards(first?40:10,first?20:5);save();renderAll();toast(`${side} ${qty} ${selected} — simulated order filled${first?' • +40 XP':''}`)}
document.addEventListener('input',e=>{if(e.target.id==='shareQty')renderOrderTotal()});
function renderPositions(){let entries=Object.entries(state.positions).filter(([,p])=>p.qty>0),el=document.getElementById('positions');el.innerHTML=entries.length?entries.map(([s,p])=>`<div class="position"><div><strong>${s}</strong><small>${p.qty} share${p.qty===1?'':'s'} • avg ${money(p.cost)}</small></div><div><strong>${money(p.qty*quotes[s].price)}</strong><small>${quotes[s].name}</small></div></div>`).join(''):'<div class="empty">No positions yet. Place a simulated buy to practice.</div>'}
function renderHistory(){let el=document.getElementById('tradeHistory');el.innerHTML=state.trades.length?state.trades.slice(0,6).map(t=>`<div class="history-item"><div><strong>${t.side} ${t.symbol}</strong><small>${new Date(t.time).toLocaleDateString()}</small></div><div><strong>${t.qty} sh</strong><small>@ ${money(t.price)}</small></div></div>`).join(''):'<div class="empty">Your simulated orders will appear here.</div>'}
function syncBadges(){if(!state)return;let before=state.earnedBadges.length;badges.forEach(b=>{if(b.test(state)&&!state.earnedBadges.includes(b.id))state.earnedBadges.push(b.id)});if(state.earnedBadges.length>before){state.coins+=(state.earnedBadges.length-before)*50;save()}}
function renderAchievements(){if(!state)return;syncBadges();document.getElementById('achievementGrid').innerHTML=badges.map(b=>{let on=state.earnedBadges.includes(b.id);return `<article class="card achievement ${on?'':'locked'}"><div class="badge-icon">${b.icon}</div><h3>${b.title}</h3><p>${b.desc}</p><div class="unlock">${on?'UNLOCKED • +50 COINS':'LOCKED'}</div></article>`}).join('')}
function showProfile(){if(!state)return;let l=xpLevel();document.getElementById('profileAvatar').textContent=state.profile.name[0].toUpperCase();document.getElementById('profileName').textContent=state.profile.name;document.getElementById('profileEmail').textContent=state.profile.email;document.getElementById('profileLevel').textContent=l.level;document.getElementById('profileXP').textContent=state.xp;document.getElementById('profileQuests').textContent=state.completed.length;document.getElementById('profileModal').classList.add('open')}
function closeProfile(){document.getElementById('profileModal').classList.remove('open')}
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2800)}
